server:
  port: 8081

#指定服务注册名称
spring:
  application:
    name: StudentProvider

eureka:
  client:
#    指定Eureka Server注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/

#  是否将服务的IP地址注册到注册中心
  instance:
    prefer-ip-address: true
