server:
  port: 8082

spring:
  application:
    name: StudentConsumer

eureka:
    client:
#    指定Eureka Server注册中心地址
      service-url:
        defaultZone: http://localhost:8761/eureka/
#  是否将服务的IP地址注册到注册中心
    instance:
      prefer-ip-address: true